name: Python Backend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.11'

jobs:
  test:
    name: Test & Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Configure Git
      run: |
        git config --global user.name "Aurora Capital CI"
        git config --global user.email "info@auroracapital.nl"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "requirements.txt not found"
        
    - name: Run linting
      run: |
        pip install flake8 black isort || echo "Linting tools not available"
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "Flake8 completed"
        black --check . || echo "Black formatting check completed"
        
    - name: Run tests
      run: |
        pip install pytest || echo "Pytest not available"
        pytest || echo "Tests completed"
        
    - name: Run security checks
      run: |
        pip install bandit safety || echo "Security tools not available"
        bandit -r . || echo "Bandit security scan completed"
        safety check || echo "Safety check completed"

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure Git
      run: |
        git config --global user.name "Aurora Capital Deploy"
        git config --global user.email "info@auroracapital.nl"
        
    - name: Deploy
      run: echo "Add your deployment commands here"
